export enum LogType {
  INIT = 'INIT',
  LINK_CREATED = 'LINK_CREATED',
  LINK_RESOLVED = 'LINK_RESOLVED',
  DEEPLINK_RESOLVED = 'DEEPLINK_RESOLVED',
  DEEPLINK_FAILED = 'DEEPLINK_FAILED',
  ATTRIBUTION = 'ATTRIBUTION',
  TRACKING = 'TRACKING',
  INFO = 'INFO',
  ERROR = 'ERROR'
}
